apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ravendb.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravendb.labels" . | nindent 4 }}
data:
  # Merge config as default, shared, node (precedence right to left)
    
  {{- $config := (include "config" .) | fromYaml }}
  
  {{- range $k, $v := .Values.hosts }}
  
  {{- $default := index $config ($k | toString) }}
  {{- $node := index $.Values.config ($k | toString )}}
  {{- $merged := mergeOverwrite (deepCopy $default) $.Values.config.shared $node }}
  
  {{- printf "%s-%s" (include "ravendb.fullname" $) $k | squote | nindent 2 }}: |
    {{- $merged | toPrettyJson | nindent 4 }}
  
  {{- end }}