apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ravendb.fullname" . }}-config
  labels:
    {{- include "ravendb.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.hosts }}
  {{- printf "%s-%s" (include "ravendb.fullname" $) $k | nindent 2 }}: |
    {
      "Setup.Mode": "None",
      "DataDir": "/data/RavenData",
      "ServerUrl": "https://0.0.0.0",
      "ServerUrl.Tcp": "tcp://0.0.0.0:38888",
      "License.Path": "/license/license.json",
      "License.Eula.Accepted": "true",
    
      "Security.Certificate.Load.Exec": "openssl",
      "Security.Certificate.Load.Exec.Arguments": "pkcs12 -inkey /tls/tls.key -in /tls/tls.crt -export -out - -nodes -passout pass:",
    
      "PublicServerUrl": "https://{{ $v.http }}/",
      "PublicServerUrl.Tcp": "https://{{ $v.tcp }}:443/",
      "Host": "{{ $v.http }}"
    }
  {{- end }}
  
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ravendb.fullname" . }}-license
  labels:
    {{- include "ravendb.labels" . | nindent 4}}
stringData:
  license.json: | 
    {{- .Values.license | nindent 4 }}
